baseURL = "https://yányào.com/"
languageCode = "en-us"
title = "yányào.com"
theme = "ezhil"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "G-LYFRPQF0H9"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Bar"
icon = "bar"
url = "/daydayup/"

[[params.social]]
name = "Radio"
icon = "radio"
url = "https://yankuiyi.com/"

[[params.social]]
name = "Inbox"
icon = "inbox"
url = "https://fouland.com/"


[[params.social]]
name = "Wind"
icon = "wind"
url = "https://at.yadanhe.com/"
